# Generated by Django 4.1.3 on 2022-12-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactus_status_user_phone_code"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="membership",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.memberships",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="user_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.usermemberships",
            ),
        ),
    ]
