# Generated by Django 4.1.3 on 2022-12-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactus_status_user_phone_code"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Gateway"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="membership",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.memberships",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="stripe_payment_intent",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Stripe ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user_membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.usermemberships",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="Payment ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="provider_order_id",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Order ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="signature_id",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Signature ID"
            ),
        ),
    ]
