# Generated by Django 4.1.3 on 2023-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_order_stripe_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="message",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Message"
            ),
        ),
    ]
