# Generated by Django 4.1.3 on 2022-11-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.AddField(
            model_name="user",
            name="age_above_18",
            field=models.BooleanField(default=False),
        ),
    ]
