# Generated by Django 4.1.3 on 2022-12-01 06:51

import random
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]
    def insertData(apps, schema_editor):
        Membershipfeatures = apps.get_model("users", "MembershipFeatures")
        
        data = [
            "Premium content",
            "Ad-Free ",
            "Device - Mobile Tab Laptop",
            "No screen limitation",
            "HD Audio quality",
            "HD video quality",
        ]
        membership_features_ids = []
        for _ in data:
            obj = Membershipfeatures(name=_)
            obj.save()
            membership_features_ids.append(obj.id)

        Memberships = apps.get_model("users", "Memberships")

        data = [
            {"name": "Starter", "validity_in_days": 7, "price_in_inr": 49.99, "price_in_dollar": 100.99},
            {"name": "Pro", "validity_in_days": 15, "price_in_inr": 99.99, "price_in_dollar": 100.99},
            {"name": "Advanced", "validity_in_days": 30, "price_in_inr": 199.99, "price_in_dollar": 100.99},
            {"name": "Experienced", "validity_in_days": 60, "price_in_inr": 499.99, "price_in_dollar": 100.99},
        ]

        for idx in data:
            obj = Memberships(
                name=idx["name"],
                validity_in_days=idx["validity_in_days"],
                price_in_inr=idx["price_in_inr"],
                price_in_dollar=idx["price_in_dollar"],
            )
            obj.save()
            _id=1
            for i in range(0, random.randint(1, 5)):
                obj.membership_features.add(_id)
                _id+=1

    operations = [
        migrations.CreateModel(
            name="MembershipFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Membership Features",
            },
        ),
        migrations.CreateModel(
            name="Memberships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("validity_in_days", models.PositiveIntegerField(default=1)),
                (
                    "price_in_inr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "price_in_dollar",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                (
                    "membership_features",
                    models.ManyToManyField(to="users.membershipfeatures"),
                ),
            ],
            options={
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.CreateModel(
            name="UserMemberships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "expiry_at",
                    models.DateTimeField(
                        blank=True, help_text="NOTE: Field will autofill when saved."
                    ),
                ),
                ("published", models.BooleanField(default=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.memberships",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Memberships",
            },
        ),
        migrations.RunPython(insertData),
    ]
