# Generated by Django 4.1.3 on 2022-12-03 10:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_membershipfeatures_memberships_usermemberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(default="IN", max_length=2),
        ),
    ]
