# Generated by Django 4.1.3 on 2022-11-26 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us Queries"},
        ),
        migrations.AlterModelOptions(
            name="loginphoneotp",
            options={"verbose_name_plural": "OTPs"},
        ),
    ]
