# Generated by Django 4.1.3 on 2022-12-11 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_contactus_status_user_phone_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[django.core.validators.MinLengthValidator(10)],
            ),
        ),
    ]
