# Generated by Django 4.1.3 on 2022-12-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoginPhoneOtp",
            new_name="LoginEmailOtp",
        ),
    ]
