# Generated by Django 4.1.3 on 2022-12-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_loginphoneotp_loginemailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="password"
            ),
        ),
    ]
