version: "3.8"

services:
    taak-frontend:
        container_name: taak-frontend
        image: taak-frontend
        build: .
        ports:
            - 80:80
        stdin_open: true
        tty: true
