version: "3.8"

services:
  mysqldb:
    image: mysql
    container_name: mysql_container
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: django_server_container
    entrypoint: ["./run_server.sh"]
    env_file: .env
    restart: always
    volumes:
      - .:/application
    depends_on:
      - mysqldb
    ports:
      - "80:8000"
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  mysql_data:
