version: "3.8"

services:
  backend:
    build: .
    container_name: django_container
    entrypoint: ["./run_server.sh"]
    env_file: .env.prod
    restart: always
    # volumes:
    #   - .:/home/docker_user/application
      # - ./logs/:/var/log
      # - ./static:/home/docker_user/application/static
      # - ./media:/home/docker_user/application/media
    volumes:
      - static-data:/home/docker_user/application/static
      - media-data:/home/docker_user/application/media
      - log-data:/home/docker_user/application/logs

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: nginx_container
    volumes:
      - static-data:/home/docker_user/application/static
      - media-data:/home/docker_user/application/media
    ports:
      - 80:80
    depends_on:
      - backend

  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "3306:3306"
    depends_on:
      - backend
volumes:
  db-data:
      driver: local
  static-data:
      driver: local
  media-data:
      driver: local
  log-data:
      driver: local