export const Routes = {
	ABOUT_US: "/api/settings/about_us/",
	PRIVACY_POLICY: "/api/settings/privacy_policy/",
	REFUND_POLICY: "/api/settings/refund_policy/",
	TERMS_AND_CONDITIONS: "/api/settings/terms_and_conditions/",
	SEND_OTP: "/api/users/send-otp/",
	VERIFY_OTP: "/api/users/verify-otp/",
	LOGOUT: "/api/users/logout/",
	CONTACT_US: "/api/users/contact_us/",
	NEWSLETTER_SUBSCRIPTION: "/api/library/newsletter_subscription/",
	HOME_PAGE_LISTINGS: "/api/library/home_page_listings/",
	WEBSITE_CONFIG: "/api/settings/website_config_settings/",
	UPCOMING: "/api/library/upcoming/",
	SEARCH: "/api/library/search/",
	PLANS: "/api/users/plans/",
	BANNER: "/api/library/banner/",
	MOVIES: "/api/library/movies",
	SERIES: "/api/library/series",
	COUNTRY_LIST: "/api/settings/country/",
	PAYMENT: "/api/payments/initiate_payments/",
};
