export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as Home } from "./home";
export { default as Policy } from "./miscellaneous/Policy";
export { default as Footer } from "./miscellaneous/Footer";
export { default as _404 } from "./miscellaneous/_404";
export { default as ContactUs } from "./contact-us";
export { default as Subscribe } from "./subscribe";
export { default as Upcoming } from "./upcoming";
